mdp:
  gamma: 1
  horizon: 1
  no_of_state_channels: 5
  no_of_action_channels: 8
  width: 160
  height: 160
  no_of_obstacles: 0
  no_of_objects: 5
  table_dimensions:
    x_min: -0.8
    x_max: 0.8
    y_min: -0.4
    y_max: 0.4
  safe_dist_from_table: 0.1
debug: True
visualize: True
render: True
render_steps: 30 #Lowest possible render steps for objects to dissapear

randomize: False
path_prefix: '/home/adamfi/codes/'
# path_prefix: '/'    # for berzelius apptainer
robot_usd_file: 'ridgeback_yumi/ridgeback_yumi.usd'
object_usd_file: 'base-pose-sequencing/assets/cube'
table_usd_file: 'base-pose-sequencing/assets/table_wood.usd'
# table_usd_file: '/Samples/Examples/FrankaNutBolt/SubUSDs/Shop_Table/Shop_Table.usd'
cube_obstacle_usd_file: 'base-pose-sequencing/assets/cube_mesh.usd'
cylinder_obstacle_usd_file: 'base-pose-sequencing/assets/cylinder_mesh.usd'
defaults:
  - motion/motion
  - grasp_poses/cube
  # - task/collect_collision_data
  # - task/collect_reachability_data
  # - task/collect_navigation_data
  - task/optimize_base_pose
  # - task/robotic_baseline



